#!/bin/bash

set -eux

runtime=`action-get time`
concurrency=`action-get concurrency`
delay=`action-get delay`
run=`date +%s`

mkdir -p /opt/siege/results/$run

benchmark-start

siege -R $CHARM_DIR/.siegerc -t ${runtime:-1M} -c ${concurrency:-25} -d ${delay:-3} -q --log=/opt/siege/results/$run/siege.log

benchmark-finish

# Parse the results
`cat /opt/siege/results/$run/siege.log | python $CHARM_DIR/actions/siege2json.py`
